name: firstworkflow

on:
    push:


jobs:
    hello:
        runs-on: ubuntu-latest
        steps:
            - run: echo "hello everyone"
            - run: echo " welcome to github actions"
            - uses: actions/checkout@v4
            - uses: actions/setup-java@v4
              with:
                distribution: 'temurin'
                java-version: '17'



